import { AIDifficulty, AIDifficultyConfig } from '../../types/ai';

export const AI_DIFFICULTIES: Record<AIDifficulty, AIDifficultyConfig> = {
  beginner: {
    id: 'beginner',
    name: 'Beginner (Novice)',
    tagline: 'Learning the rules, makes frequent tactical blunders',
    depth: 1,
    skillLevel: 2,
    minThinkingMs: 300,
    maxThinkingMs: 500,
    estimatedElo: 800,
    avatarIcon: '🌱',
    badgeColor: 'bg-emerald-500/10 text-emerald-500 border-emerald-500/20',
  },
  easy: {
    id: 'easy',
    name: 'Easy (Casual)',
    tagline: 'Plays basic developing moves with occasional oversights',
    depth: 2,
    skillLevel: 6,
    minThinkingMs: 400,
    maxThinkingMs: 700,
    estimatedElo: 1200,
    avatarIcon: '🥉',
    badgeColor: 'bg-blue-500/10 text-blue-500 border-blue-500/20',
  },
  medium: {
    id: 'medium',
    name: 'Medium (Club Player)',
    tagline: 'Solid positional understanding and tactical awareness',
    depth: 3,
    skillLevel: 11,
    minThinkingMs: 500,
    maxThinkingMs: 1000,
    estimatedElo: 1600,
    avatarIcon: '🥈',
    badgeColor: 'bg-amber-500/10 text-amber-500 border-amber-500/20',
  },
  hard: {
    id: 'hard',
    name: 'Hard (Master)',
    tagline: 'Deep tactical vision, sharp defenses, and strong endgames',
    depth: 4,
    skillLevel: 16,
    minThinkingMs: 700,
    maxThinkingMs: 1400,
    estimatedElo: 2000,
    avatarIcon: '🥇',
    badgeColor: 'bg-purple-500/10 text-purple-500 border-purple-500/20',
  },
  expert: {
    id: 'expert',
    name: 'Expert (Grandmaster)',
    tagline: 'Maximum search depth and near-flawless engine calculation',
    depth: 5,
    skillLevel: 20,
    minThinkingMs: 900,
    maxThinkingMs: 1800,
    estimatedElo: 2400,
    avatarIcon: '👑',
    badgeColor: 'bg-rose-500/10 text-rose-500 border-rose-500/20',
  },
};

export const DEFAULT_AI_DIFFICULTY: AIDifficulty = 'medium';
